/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedCommissionsRouteImport } from './routes/_authenticated/commissions'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedMaterialsRouteImport } from './routes/_authenticated/materials'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedTodayRouteImport } from './routes/_authenticated/today'
import { Route as AuthenticatedWorkRouteImport } from './routes/_authenticated/work'
import { Route as AuthenticatedLeadsIndexRouteImport } from './routes/_authenticated/leads.index'
import { Route as AuthenticatedLeadsCommissionsRouteImport } from './routes/_authenticated/leads.commissions'
import { Route as AuthenticatedLeadsCustomersRouteImport } from './routes/_authenticated/leads.customers'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects.index'
import { Route as AuthenticatedProjectsProjectIdRouteImport } from './routes/_authenticated/projects.$projectId'
import { Route as AuthenticatedWorkItemIdRouteImport } from './routes/_authenticated/work.$itemId'
import { Route as ApiPublicQaProvisionRouteImport } from './routes/api/public/qa-provision'
import { Route as AuthenticatedProjectsProjectIdIndexRouteImport } from './routes/_authenticated/projects.$projectId.index'
import { Route as AuthenticatedProjectsProjectIdDesignRouteImport } from './routes/_authenticated/projects.$projectId.design'
import { Route as AuthenticatedProjectsProjectIdFieldRouteImport } from './routes/_authenticated/projects.$projectId.field'
import { Route as AuthenticatedProjectsProjectIdFilesRouteImport } from './routes/_authenticated/projects.$projectId.files'
import { Route as AuthenticatedProjectsProjectIdInstallMaterialsRouteImport } from './routes/_authenticated/projects.$projectId.install-materials'
import { Route as AuthenticatedProjectsProjectIdMaterialsRouteImport } from './routes/_authenticated/projects.$projectId.materials'
import { Route as AuthenticatedProjectsProjectIdPackageRouteImport } from './routes/_authenticated/projects.$projectId.package'
import { Route as AuthenticatedProjectsProjectIdScheduleRouteImport } from './routes/_authenticated/projects.$projectId.schedule'
import { Route as AuthenticatedProjectsProjectIdScopeRouteImport } from './routes/_authenticated/projects.$projectId.scope'
import { Route as AuthenticatedProjectsProjectIdTasksRouteImport } from './routes/_authenticated/projects.$projectId.tasks'
import { Route as AuthenticatedProjectsProjectIdTilesRouteImport } from './routes/_authenticated/projects.$projectId.tiles'
import { Route as AuthenticatedProjectsProjectIdUpdatesRouteImport } from './routes/_authenticated/projects.$projectId.updates'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCommissionsRoute =
  AuthenticatedCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaterialsRoute = AuthenticatedMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTodayRoute = AuthenticatedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkRoute = AuthenticatedWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsIndexRoute = AuthenticatedLeadsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedLeadsRoute,
} as any)
const AuthenticatedLeadsCommissionsRoute =
  AuthenticatedLeadsCommissionsRouteImport.update({
    id: '/commissions',
    path: '/commissions',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any)
const AuthenticatedLeadsCustomersRoute =
  AuthenticatedLeadsCustomersRouteImport.update({
    id: '/customers',
    path: '/customers',
    getParentRoute: () => AuthenticatedLeadsRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProjectsProjectIdRoute =
  AuthenticatedProjectsProjectIdRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedWorkItemIdRoute = AuthenticatedWorkItemIdRouteImport.update({
  id: '/$itemId',
  path: '/$itemId',
  getParentRoute: () => AuthenticatedWorkRoute,
} as any)
const ApiPublicQaProvisionRoute = ApiPublicQaProvisionRouteImport.update({
  id: '/api/public/qa-provision',
  path: '/api/public/qa-provision',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProjectsProjectIdIndexRoute =
  AuthenticatedProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdDesignRoute =
  AuthenticatedProjectsProjectIdDesignRouteImport.update({
    id: '/design',
    path: '/design',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdFieldRoute =
  AuthenticatedProjectsProjectIdFieldRouteImport.update({
    id: '/field',
    path: '/field',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdFilesRoute =
  AuthenticatedProjectsProjectIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdInstallMaterialsRoute =
  AuthenticatedProjectsProjectIdInstallMaterialsRouteImport.update({
    id: '/install-materials',
    path: '/install-materials',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdMaterialsRoute =
  AuthenticatedProjectsProjectIdMaterialsRouteImport.update({
    id: '/materials',
    path: '/materials',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdPackageRoute =
  AuthenticatedProjectsProjectIdPackageRouteImport.update({
    id: '/package',
    path: '/package',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdScheduleRoute =
  AuthenticatedProjectsProjectIdScheduleRouteImport.update({
    id: '/schedule',
    path: '/schedule',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdScopeRoute =
  AuthenticatedProjectsProjectIdScopeRouteImport.update({
    id: '/scope',
    path: '/scope',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTasksRoute =
  AuthenticatedProjectsProjectIdTasksRouteImport.update({
    id: '/tasks',
    path: '/tasks',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdTilesRoute =
  AuthenticatedProjectsProjectIdTilesRouteImport.update({
    id: '/tiles',
    path: '/tiles',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)
const AuthenticatedProjectsProjectIdUpdatesRoute =
  AuthenticatedProjectsProjectIdUpdatesRouteImport.update({
    id: '/updates',
    path: '/updates',
    getParentRoute: () => AuthenticatedProjectsProjectIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/materials': typeof AuthenticatedMaterialsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/work': typeof AuthenticatedWorkRouteWithChildren
  '/leads/commissions': typeof AuthenticatedLeadsCommissionsRoute
  '/leads/customers': typeof AuthenticatedLeadsCustomersRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/work/$itemId': typeof AuthenticatedWorkItemIdRoute
  '/api/public/qa-provision': typeof ApiPublicQaProvisionRoute
  '/leads/': typeof AuthenticatedLeadsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/design': typeof AuthenticatedProjectsProjectIdDesignRoute
  '/projects/$projectId/field': typeof AuthenticatedProjectsProjectIdFieldRoute
  '/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/projects/$projectId/install-materials': typeof AuthenticatedProjectsProjectIdInstallMaterialsRoute
  '/projects/$projectId/materials': typeof AuthenticatedProjectsProjectIdMaterialsRoute
  '/projects/$projectId/package': typeof AuthenticatedProjectsProjectIdPackageRoute
  '/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/projects/$projectId/scope': typeof AuthenticatedProjectsProjectIdScopeRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/tiles': typeof AuthenticatedProjectsProjectIdTilesRoute
  '/projects/$projectId/updates': typeof AuthenticatedProjectsProjectIdUpdatesRoute
  '/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/commissions': typeof AuthenticatedCommissionsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/materials': typeof AuthenticatedMaterialsRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/today': typeof AuthenticatedTodayRoute
  '/work': typeof AuthenticatedWorkRouteWithChildren
  '/leads/commissions': typeof AuthenticatedLeadsCommissionsRoute
  '/leads/customers': typeof AuthenticatedLeadsCustomersRoute
  '/work/$itemId': typeof AuthenticatedWorkItemIdRoute
  '/api/public/qa-provision': typeof ApiPublicQaProvisionRoute
  '/leads': typeof AuthenticatedLeadsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/projects/$projectId/design': typeof AuthenticatedProjectsProjectIdDesignRoute
  '/projects/$projectId/field': typeof AuthenticatedProjectsProjectIdFieldRoute
  '/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/projects/$projectId/install-materials': typeof AuthenticatedProjectsProjectIdInstallMaterialsRoute
  '/projects/$projectId/materials': typeof AuthenticatedProjectsProjectIdMaterialsRoute
  '/projects/$projectId/package': typeof AuthenticatedProjectsProjectIdPackageRoute
  '/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/projects/$projectId/scope': typeof AuthenticatedProjectsProjectIdScopeRoute
  '/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/projects/$projectId/tiles': typeof AuthenticatedProjectsProjectIdTilesRoute
  '/projects/$projectId/updates': typeof AuthenticatedProjectsProjectIdUpdatesRoute
  '/projects/$projectId': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/commissions': typeof AuthenticatedCommissionsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRouteWithChildren
  '/_authenticated/materials': typeof AuthenticatedMaterialsRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/today': typeof AuthenticatedTodayRoute
  '/_authenticated/work': typeof AuthenticatedWorkRouteWithChildren
  '/_authenticated/leads/commissions': typeof AuthenticatedLeadsCommissionsRoute
  '/_authenticated/leads/customers': typeof AuthenticatedLeadsCustomersRoute
  '/_authenticated/projects/$projectId': typeof AuthenticatedProjectsProjectIdRouteWithChildren
  '/_authenticated/work/$itemId': typeof AuthenticatedWorkItemIdRoute
  '/api/public/qa-provision': typeof ApiPublicQaProvisionRoute
  '/_authenticated/leads/': typeof AuthenticatedLeadsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/projects/$projectId/design': typeof AuthenticatedProjectsProjectIdDesignRoute
  '/_authenticated/projects/$projectId/field': typeof AuthenticatedProjectsProjectIdFieldRoute
  '/_authenticated/projects/$projectId/files': typeof AuthenticatedProjectsProjectIdFilesRoute
  '/_authenticated/projects/$projectId/install-materials': typeof AuthenticatedProjectsProjectIdInstallMaterialsRoute
  '/_authenticated/projects/$projectId/materials': typeof AuthenticatedProjectsProjectIdMaterialsRoute
  '/_authenticated/projects/$projectId/package': typeof AuthenticatedProjectsProjectIdPackageRoute
  '/_authenticated/projects/$projectId/schedule': typeof AuthenticatedProjectsProjectIdScheduleRoute
  '/_authenticated/projects/$projectId/scope': typeof AuthenticatedProjectsProjectIdScopeRoute
  '/_authenticated/projects/$projectId/tasks': typeof AuthenticatedProjectsProjectIdTasksRoute
  '/_authenticated/projects/$projectId/tiles': typeof AuthenticatedProjectsProjectIdTilesRoute
  '/_authenticated/projects/$projectId/updates': typeof AuthenticatedProjectsProjectIdUpdatesRoute
  '/_authenticated/projects/$projectId/': typeof AuthenticatedProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/commissions'
    | '/dashboard'
    | '/leads'
    | '/materials'
    | '/schedule'
    | '/settings'
    | '/today'
    | '/work'
    | '/leads/commissions'
    | '/leads/customers'
    | '/projects/$projectId'
    | '/work/$itemId'
    | '/api/public/qa-provision'
    | '/leads/'
    | '/projects/'
    | '/projects/$projectId/design'
    | '/projects/$projectId/field'
    | '/projects/$projectId/files'
    | '/projects/$projectId/install-materials'
    | '/projects/$projectId/materials'
    | '/projects/$projectId/package'
    | '/projects/$projectId/schedule'
    | '/projects/$projectId/scope'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tiles'
    | '/projects/$projectId/updates'
    | '/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/commissions'
    | '/dashboard'
    | '/materials'
    | '/schedule'
    | '/settings'
    | '/today'
    | '/work'
    | '/leads/commissions'
    | '/leads/customers'
    | '/work/$itemId'
    | '/api/public/qa-provision'
    | '/leads'
    | '/projects'
    | '/projects/$projectId/design'
    | '/projects/$projectId/field'
    | '/projects/$projectId/files'
    | '/projects/$projectId/install-materials'
    | '/projects/$projectId/materials'
    | '/projects/$projectId/package'
    | '/projects/$projectId/schedule'
    | '/projects/$projectId/scope'
    | '/projects/$projectId/tasks'
    | '/projects/$projectId/tiles'
    | '/projects/$projectId/updates'
    | '/projects/$projectId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/commissions'
    | '/_authenticated/dashboard'
    | '/_authenticated/leads'
    | '/_authenticated/materials'
    | '/_authenticated/schedule'
    | '/_authenticated/settings'
    | '/_authenticated/today'
    | '/_authenticated/work'
    | '/_authenticated/leads/commissions'
    | '/_authenticated/leads/customers'
    | '/_authenticated/projects/$projectId'
    | '/_authenticated/work/$itemId'
    | '/api/public/qa-provision'
    | '/_authenticated/leads/'
    | '/_authenticated/projects/'
    | '/_authenticated/projects/$projectId/design'
    | '/_authenticated/projects/$projectId/field'
    | '/_authenticated/projects/$projectId/files'
    | '/_authenticated/projects/$projectId/install-materials'
    | '/_authenticated/projects/$projectId/materials'
    | '/_authenticated/projects/$projectId/package'
    | '/_authenticated/projects/$projectId/schedule'
    | '/_authenticated/projects/$projectId/scope'
    | '/_authenticated/projects/$projectId/tasks'
    | '/_authenticated/projects/$projectId/tiles'
    | '/_authenticated/projects/$projectId/updates'
    | '/_authenticated/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicQaProvisionRoute: typeof ApiPublicQaProvisionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/commissions': {
      id: '/_authenticated/commissions'
      path: '/commissions'
      fullPath: '/commissions'
      preLoaderRoute: typeof AuthenticatedCommissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/materials': {
      id: '/_authenticated/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AuthenticatedMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/today': {
      id: '/_authenticated/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthenticatedTodayRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work': {
      id: '/_authenticated/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof AuthenticatedWorkRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads/': {
      id: '/_authenticated/leads/'
      path: '/'
      fullPath: '/leads/'
      preLoaderRoute: typeof AuthenticatedLeadsIndexRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/leads/commissions': {
      id: '/_authenticated/leads/commissions'
      path: '/commissions'
      fullPath: '/leads/commissions'
      preLoaderRoute: typeof AuthenticatedLeadsCommissionsRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/leads/customers': {
      id: '/_authenticated/leads/customers'
      path: '/customers'
      fullPath: '/leads/customers'
      preLoaderRoute: typeof AuthenticatedLeadsCustomersRouteImport
      parentRoute: typeof AuthenticatedLeadsRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/projects/$projectId': {
      id: '/_authenticated/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/work/$itemId': {
      id: '/_authenticated/work/$itemId'
      path: '/$itemId'
      fullPath: '/work/$itemId'
      preLoaderRoute: typeof AuthenticatedWorkItemIdRouteImport
      parentRoute: typeof AuthenticatedWorkRoute
    }
    '/api/public/qa-provision': {
      id: '/api/public/qa-provision'
      path: '/api/public/qa-provision'
      fullPath: '/api/public/qa-provision'
      preLoaderRoute: typeof ApiPublicQaProvisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/projects/$projectId/': {
      id: '/_authenticated/projects/$projectId/'
      path: '/'
      fullPath: '/projects/$projectId/'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/design': {
      id: '/_authenticated/projects/$projectId/design'
      path: '/design'
      fullPath: '/projects/$projectId/design'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdDesignRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/field': {
      id: '/_authenticated/projects/$projectId/field'
      path: '/field'
      fullPath: '/projects/$projectId/field'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFieldRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/files': {
      id: '/_authenticated/projects/$projectId/files'
      path: '/files'
      fullPath: '/projects/$projectId/files'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdFilesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/install-materials': {
      id: '/_authenticated/projects/$projectId/install-materials'
      path: '/install-materials'
      fullPath: '/projects/$projectId/install-materials'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdInstallMaterialsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/materials': {
      id: '/_authenticated/projects/$projectId/materials'
      path: '/materials'
      fullPath: '/projects/$projectId/materials'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdMaterialsRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/package': {
      id: '/_authenticated/projects/$projectId/package'
      path: '/package'
      fullPath: '/projects/$projectId/package'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdPackageRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/schedule': {
      id: '/_authenticated/projects/$projectId/schedule'
      path: '/schedule'
      fullPath: '/projects/$projectId/schedule'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScheduleRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/scope': {
      id: '/_authenticated/projects/$projectId/scope'
      path: '/scope'
      fullPath: '/projects/$projectId/scope'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdScopeRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tasks': {
      id: '/_authenticated/projects/$projectId/tasks'
      path: '/tasks'
      fullPath: '/projects/$projectId/tasks'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTasksRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/tiles': {
      id: '/_authenticated/projects/$projectId/tiles'
      path: '/tiles'
      fullPath: '/projects/$projectId/tiles'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdTilesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
    '/_authenticated/projects/$projectId/updates': {
      id: '/_authenticated/projects/$projectId/updates'
      path: '/updates'
      fullPath: '/projects/$projectId/updates'
      preLoaderRoute: typeof AuthenticatedProjectsProjectIdUpdatesRouteImport
      parentRoute: typeof AuthenticatedProjectsProjectIdRoute
    }
  }
}

interface AuthenticatedLeadsRouteChildren {
  AuthenticatedLeadsCommissionsRoute: typeof AuthenticatedLeadsCommissionsRoute
  AuthenticatedLeadsCustomersRoute: typeof AuthenticatedLeadsCustomersRoute
  AuthenticatedLeadsIndexRoute: typeof AuthenticatedLeadsIndexRoute
}

const AuthenticatedLeadsRouteChildren: AuthenticatedLeadsRouteChildren = {
  AuthenticatedLeadsCommissionsRoute: AuthenticatedLeadsCommissionsRoute,
  AuthenticatedLeadsCustomersRoute: AuthenticatedLeadsCustomersRoute,
  AuthenticatedLeadsIndexRoute: AuthenticatedLeadsIndexRoute,
}

const AuthenticatedLeadsRouteWithChildren =
  AuthenticatedLeadsRoute._addFileChildren(AuthenticatedLeadsRouteChildren)

interface AuthenticatedWorkRouteChildren {
  AuthenticatedWorkItemIdRoute: typeof AuthenticatedWorkItemIdRoute
}

const AuthenticatedWorkRouteChildren: AuthenticatedWorkRouteChildren = {
  AuthenticatedWorkItemIdRoute: AuthenticatedWorkItemIdRoute,
}

const AuthenticatedWorkRouteWithChildren =
  AuthenticatedWorkRoute._addFileChildren(AuthenticatedWorkRouteChildren)

interface AuthenticatedProjectsProjectIdRouteChildren {
  AuthenticatedProjectsProjectIdDesignRoute: typeof AuthenticatedProjectsProjectIdDesignRoute
  AuthenticatedProjectsProjectIdFieldRoute: typeof AuthenticatedProjectsProjectIdFieldRoute
  AuthenticatedProjectsProjectIdFilesRoute: typeof AuthenticatedProjectsProjectIdFilesRoute
  AuthenticatedProjectsProjectIdInstallMaterialsRoute: typeof AuthenticatedProjectsProjectIdInstallMaterialsRoute
  AuthenticatedProjectsProjectIdMaterialsRoute: typeof AuthenticatedProjectsProjectIdMaterialsRoute
  AuthenticatedProjectsProjectIdPackageRoute: typeof AuthenticatedProjectsProjectIdPackageRoute
  AuthenticatedProjectsProjectIdScheduleRoute: typeof AuthenticatedProjectsProjectIdScheduleRoute
  AuthenticatedProjectsProjectIdScopeRoute: typeof AuthenticatedProjectsProjectIdScopeRoute
  AuthenticatedProjectsProjectIdTasksRoute: typeof AuthenticatedProjectsProjectIdTasksRoute
  AuthenticatedProjectsProjectIdTilesRoute: typeof AuthenticatedProjectsProjectIdTilesRoute
  AuthenticatedProjectsProjectIdUpdatesRoute: typeof AuthenticatedProjectsProjectIdUpdatesRoute
  AuthenticatedProjectsProjectIdIndexRoute: typeof AuthenticatedProjectsProjectIdIndexRoute
}

const AuthenticatedProjectsProjectIdRouteChildren: AuthenticatedProjectsProjectIdRouteChildren =
  {
    AuthenticatedProjectsProjectIdDesignRoute:
      AuthenticatedProjectsProjectIdDesignRoute,
    AuthenticatedProjectsProjectIdFieldRoute:
      AuthenticatedProjectsProjectIdFieldRoute,
    AuthenticatedProjectsProjectIdFilesRoute:
      AuthenticatedProjectsProjectIdFilesRoute,
    AuthenticatedProjectsProjectIdInstallMaterialsRoute:
      AuthenticatedProjectsProjectIdInstallMaterialsRoute,
    AuthenticatedProjectsProjectIdMaterialsRoute:
      AuthenticatedProjectsProjectIdMaterialsRoute,
    AuthenticatedProjectsProjectIdPackageRoute:
      AuthenticatedProjectsProjectIdPackageRoute,
    AuthenticatedProjectsProjectIdScheduleRoute:
      AuthenticatedProjectsProjectIdScheduleRoute,
    AuthenticatedProjectsProjectIdScopeRoute:
      AuthenticatedProjectsProjectIdScopeRoute,
    AuthenticatedProjectsProjectIdTasksRoute:
      AuthenticatedProjectsProjectIdTasksRoute,
    AuthenticatedProjectsProjectIdTilesRoute:
      AuthenticatedProjectsProjectIdTilesRoute,
    AuthenticatedProjectsProjectIdUpdatesRoute:
      AuthenticatedProjectsProjectIdUpdatesRoute,
    AuthenticatedProjectsProjectIdIndexRoute:
      AuthenticatedProjectsProjectIdIndexRoute,
  }

const AuthenticatedProjectsProjectIdRouteWithChildren =
  AuthenticatedProjectsProjectIdRoute._addFileChildren(
    AuthenticatedProjectsProjectIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCommissionsRoute: typeof AuthenticatedCommissionsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRouteWithChildren
  AuthenticatedMaterialsRoute: typeof AuthenticatedMaterialsRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTodayRoute: typeof AuthenticatedTodayRoute
  AuthenticatedWorkRoute: typeof AuthenticatedWorkRouteWithChildren
  AuthenticatedProjectsProjectIdRoute: typeof AuthenticatedProjectsProjectIdRouteWithChildren
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCommissionsRoute: AuthenticatedCommissionsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRouteWithChildren,
  AuthenticatedMaterialsRoute: AuthenticatedMaterialsRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTodayRoute: AuthenticatedTodayRoute,
  AuthenticatedWorkRoute: AuthenticatedWorkRouteWithChildren,
  AuthenticatedProjectsProjectIdRoute:
    AuthenticatedProjectsProjectIdRouteWithChildren,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicQaProvisionRoute: ApiPublicQaProvisionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
